version: '3.8'
services:
  hoopstreet:
    build: .
    volumes:
      - ./data:/root/.hoopstreet
      - ./backups:/root/ish-dev/backups
    environment:
      - TZ=Asia/Manila
    stdin_open: true
    tty: true
