#!/bin/bash
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🏀 HOOPSTREET HELP SYSTEM v9.3.2"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 AVAILABLE COMMANDS:"
echo ""
echo "   /root/menu                    - Launch main menu"
echo "   /root/ish-dev/core/status.sh  - System status"
echo "   /root/ish-dev/core/heal.sh    - Auto-heal bugs"
echo "   /root/ish-dev/core/sync.sh    - Sync to GitHub"
echo ""
echo "📝 CODE EXECUTOR FORMAT:"
echo ""
echo "   # Phase 1"
echo "   echo \"Your command here\""
echo "   # Phase 2"
echo "   echo \"Next command\""
echo "   END"
echo ""
echo "🔧 TROUBLESHOOTING:"
echo ""
echo "   Issue: Menu not showing"
echo "   Fix:   ln -sf /root/ish-dev/core/menu.sh /root/menu"
echo ""
echo "   Issue: Git push fails"
echo "   Fix:   Check token in Option 6"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
