#!/bin/sh
clear
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║     🤖 iSH AUTO HEALING AGENT - COMPLETE SYSTEM             ║"
echo "║                                                              ║"
echo "║     • 5 Gemini Keys + OpenRouter Backup                     ║"
echo "║     • Auto Phase Detection & Execution                      ║"
echo "║     • Self-Healing Code                                     ║"
echo "║     • DNA Logging                                           ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo ""
echo "  🎮 Available Commands:"
echo "  ─────────────────────────────────────────────────────────────"
echo ""
echo "    /root/master_phase.sh    - Run phase executor (paste code)"
echo "    /root/prompt_loop.sh     - Interactive command loop"
echo "    /root/run_summary.sh     - Run healing agent with menu"
echo "    /root/run_complete_setup.sh - Complete setup & test"
echo ""
echo "  📝 Quick Start:"
echo "  ─────────────────────────────────────────────────────────────"
echo ""
echo "    1. Start interactive loop:    /root/prompt_loop.sh"
echo "    2. Run phase executor:        type 'master' at prompt"
echo "    3. Test healing:              type 'heal' at prompt"
echo "    4. Check status:              type 'status' at prompt"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
printf "localhost:~# "
