#!/bin/sh
clear
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║     🤖 iSH AUTO HEALING AGENT v4.0 - READY                   ║"
echo "║                                                              ║"
echo "║     • 5 Gemini Keys + OpenRouter Backup                      ║"
echo "║     • Auto Phase Detection & Execution                       ║"
echo "║     • Spinners + Auto-Retry + DNA Logging                    ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📋 QUICK START"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Type 'start' to open the agent menu"
echo "  Or directly paste your multi-phase code:"
echo ""
echo "  Example:"
echo "    # Phase 1"
echo "    echo 'Hello'"
echo "    # Phase 2"
echo "    echo 'World'"
echo "    END"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
printf "localhost:~# "
