#!/bin/sh
clear
echo "════════════════════════════════════════════════════════"
echo "     📊 STATUS DASHBOARD"
echo "════════════════════════════════════════════════════════"
echo ""
echo "📋 RECENT LOGS:"
echo "─────────────────────────────────────────────────────────"
tail -10 /root/ish-dev/logs.txt 2>/dev/null || echo "No logs"
echo ""
echo "🧬 DNA.md (last 10):"
echo "─────────────────────────────────────────────────────────"
tail -10 /root/ish-dev/DNA.md 2>/dev/null || echo "No DNA"
echo ""
read -p "Press Enter to continue..."
